### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by wanglixilinx** [jianpengz/DoDNet#1]
Hi. @jianpengz ,，
  Thx very much for your work. Currently, I just use this repro, and occur some problems when downloading the dataset as your instruction.
1.) I do not find any data related with Kidney dataset;
2) I just download Lits and found that are different with your data folder format  in the  lits/MOTS/MOTS_train/test.txt

**Comment by jianpengz** [comment]
Thanks for your attention. 
1. The link to the kidney dataset has been updated. Please try again. 
2. After downloading these datasets, put them in 'dataset/0123456/' and change the folder name, like '0Liver', '1Kidney'. Your data path should be consistent with the list file.

**Comment by wanglixilinx** [comment]
Hi， thanks for you reply. for the Liver dataset, my data folder is listed as below:
train./Train-part1.zip
train./Train-part2.zip
train./Train-part3.zip
train./Train-part4.zip
train./Train-part5.zip
train./Train-part6.zip


Is  it ok ?

**Comment by jianpengz** [comment]
I think it should be like

dataset/0123456_spacing_same/
├── 0Liver
          └── imagesTr
                     ├── liver_0.nii.gz
                     ├── liver_1.nii.gz
                     ├── ...
          └── labelsTr
                     ├── liver_0.nii.gz
                     ├── liver_1.nii.gz
                     ├── ...
├── 1Kidney
├── ...

**Comment by jianpengz** [comment]
I think it should be like
<img width="219" alt="WeChatd011ae95976ce1e5ccb33989ade8371d" src="https://user-images.githubusercontent.com/21073209/110738008-6fe99000-827e-11eb-9a8c-4a46a4e3ee12.png">

**Comment by wanglixilinx** [comment]
Following your link, I download the data just as I listed above.   Can you share your Liver dataset with me?

**Comment by jianpengz** [comment]
Please try to download via this Google drive link: [https://drive.google.com/drive/folders/0B0vscETPGI1-Q1h1WFdEM2FHSUE]. The items in this link should be like

![image](https://user-images.githubusercontent.com/21073209/111094102-69169200-858a-11eb-9169-2bb80edaf52c.png)

**Comment by arinaruck** [comment]
Hello, @jianpengz! I'm dealing with the same issue right now:
![image](https://user-images.githubusercontent.com/22507422/121073004-4afbaf00-c7d2-11eb-8ba2-a75bc437fca7.png)

The image data is in the way you are listing it, but it is not following the LabelsTr, ImagesTr structure:
![image](https://user-images.githubusercontent.com/22507422/121073138-72eb1280-c7d2-11eb-9613-82023c6cff65.png)

How should the code be fixed for that case? And how exactly should the LiTS data be stored then? 
Like: 0Liver/Training Batch 1, 0Liver/Training Batch 2?
Thanks

**Comment by arinaruck** [comment]
@jianpengz, would you also mind clarifying about the 1Kidney? Based on the GitHub, providing the data it is stored as follows:
![image](https://user-images.githubusercontent.com/22507422/121090893-8786d500-c7e9-11eb-82a4-e42302d34573.png)
Nevertheless, there is an if condition for the 1Kidney case, which is never satisfied, since there is no 'origin' in the data structure
Maybe there is some additional step before re_spacing, which I am missing?
I would also suggest rewriting the re_spacing code to multy processing pipeline, and I would be happy to do it as soon as the original preprocessing version works
Thanks for your work

**Comment by jianpengz** [comment]
Hi @arinaruck,
LiTS dataset has a different storage format from the MSD style. A simple solution is using the MSD style LiTS dataset from MSD challenge (both of them are the same). 
As for kidney dataset, I renamed the data/ folder as origin/ due to some reasons a long time ago. You can rename the download data/ as origin/ to work well.

**Comment by arinaruck** [comment]
@jianpengz Thank you!

**Comment by arinaruck** [comment]
@jianpengz, Sorry to bother you again, but shouldn't there be an `else:` or `continue` for the kidney case: https://github.com/jianpengz/DoDNet/blob/956d2558fc6e9e786260590d0e5c7843edd95f32/dataset/re_spacing.py#L28
Seems like the next for loop is for MSD only? I've just added a pull request fixing it if it indeed is the case. 
Please correct me, if I misinterpreted the code
